-- ============================================================================
-- Performance index review - verified gaps only. NOT auto-applied.
-- ============================================================================
-- This file lives under docs/ (NOT supabase/migrations/) on purpose, so
-- `supabase db push` will NOT run it.
--
-- IMPORTANT:
-- - Verify live indexes before applying any statement below.
-- - Run CREATE INDEX CONCURRENTLY only outside a transaction.
-- - The Supabase migration runner wraps migrations in a transaction, so run
--   any needed CONCURRENTLY statement manually in the Supabase SQL Editor after
--   backup/rollback has been confirmed.
-- - `IF NOT EXISTS` only checks the index name, not equivalent indexes. Do not
--   run these if an existing primary key, unique index, or composite index
--   already covers the access pattern.
--
-- Verification query:
--   select schemaname, tablename, indexname, indexdef
--   from pg_indexes
--   where schemaname = 'public'
--     and tablename in ('poll_votes', 'user_avatar_inventory', 'chat_reports')
--   order by tablename, indexname;
--
-- Linked production verification on 2026-07-06 found:
-- - poll_votes_unique_user_poll on (user_id, poll_id) where user_id is not null
-- - user_avatar_inventory_pkey on (user_id, avatar_id)
-- - chat_reports_status_idx on (status, created_at desc)
--
-- Result: no new indexes are needed in the linked production database.
-- ============================================================================

-- 1) poll_votes(user_id)
-- Helps: profile stats queries that filter votes by user_id, e.g.
--        get_profile_stats() counting rows from public.poll_votes where user_id = p_user_id.
-- Current linked DB status: SKIP. Covered by:
--        poll_votes_unique_user_poll (user_id, poll_id) where user_id is not null.
-- Only run this in another environment if no existing index starts with user_id:
-- CREATE INDEX CONCURRENTLY IF NOT EXISTS poll_votes_user_id_idx
--   ON public.poll_votes (user_id);

-- 2) user_avatar_inventory(user_id)
-- Helps: inventory/store/profile queries loading owned avatars for the current user:
--        select avatar_id from public.user_avatar_inventory where user_id = $1.
-- Current linked DB status: SKIP. Covered by:
--        user_avatar_inventory_pkey (user_id, avatar_id).
-- Only run this in another environment if the primary key/index does not start with user_id:
-- CREATE INDEX CONCURRENTLY IF NOT EXISTS user_avatar_inventory_user_id_idx
--   ON public.user_avatar_inventory (user_id);

-- 3) chat_reports(status, created_at desc)
-- Helps: admin moderation queue queries filtering by status and ordering newest first.
-- Current linked DB status: SKIP. Covered by:
--        chat_reports_status_idx (status, created_at desc).
-- Only run this in another environment if no existing index covers both status and ordering:
-- CREATE INDEX CONCURRENTLY IF NOT EXISTS chat_reports_status_created_idx
--   ON public.chat_reports (status, created_at DESC);
